{{- if .Values.limitRange.managedByHelm | default true }}
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ include "sa-platform.fullname" . }}-limits
  namespace: {{ .Values.global.namespace | quote }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.defaultCpu | default "250m" | quote }}
        memory: {{ .Values.limitRange.defaultMemory | default "256Mi" | quote }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequestCpu | default "100m" | quote }}
        memory: {{ .Values.limitRange.defaultRequestMemory | default "128Mi" | quote }}
      max:
        cpu: {{ .Values.limitRange.maxCpu | default "1" | quote }}
        memory: {{ .Values.limitRange.maxMemory | default "1Gi" | quote }}
      min:
        cpu: {{ .Values.limitRange.minCpu | default "50m" | quote }}
        memory: {{ .Values.limitRange.minMemory | default "64Mi" | quote }}
{{- end }}
