apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sa-platform.fullname" . }}-app-secrets
  namespace: {{ .Values.global.namespace | quote }}
  labels:
    {{- include "sa-platform.labels" (dict "root" . "component" "app-secrets") | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ required "secrets.db.user es requerido (ver values.example.yaml)" .Values.secrets.db.user | quote }}
  DB_PASSWORD: {{ required "secrets.db.password es requerido (ver values.example.yaml)" .Values.secrets.db.password | quote }}
  BROKER_USER: {{ required "secrets.broker.user es requerido (ver values.example.yaml)" .Values.secrets.broker.user | quote }}
  BROKER_PASSWORD: {{ required "secrets.broker.password es requerido (ver values.example.yaml)" .Values.secrets.broker.password | quote }}
  JWT_SECRET: {{ required "secrets.jwtSecret es requerido (ver values.example.yaml)" .Values.secrets.jwtSecret | quote }}
