apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-frontend-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "sa-platform.labels" (dict "root" . "component" "frontend") | nindent 4 }}
data:
  NOTE: "frontend estatico, sin variables de configuracion propias"
