apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-frontend-pdb
  namespace: {{ .Values.global.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "sa-platform.selectorLabels" (dict "component" "frontend") | nindent 6 }}
