apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "sa-platform.labels" (dict "root" . "component" "api-gateway") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sa-platform.selectorLabels" (dict "component" "api-gateway") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 8080 }}
      targetPort: http
