apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-aprobaciones-service
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "sa-platform.labels" (dict "root" . "component" "aprobaciones-service") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "sa-platform.selectorLabels" (dict "component" "aprobaciones-service") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port | default 4003 }}
      targetPort: http
